# Utility functions for File I/O and summary reporting

import json
import os

def export_json_data(data, export_path):
    """Write data to export_path as JSON, creating the folder if needed.
    Returns (ok, message)."""
    try:
        # Resolve folder path
        parent_dir = os.path.dirname(export_path)
        if parent_dir and not os.path.exists(parent_dir):
            os.makedirs(parent_dir)
            
        with open(export_path, 'w') as f:
            json.dump(data, f, indent=3)
        return True, "Export successful!"
    except Exception as e:
        return False, f"Failed to export: {str(e)}"

def generate_clinical_summary(data):
    """Build a plain-text summary of the Cobb results. Only used by the
    retired wizard UI (modules/pages.py)."""
    summary = []
    summary.append("==================================================")
    summary.append("       SCOLIOSIS ASSESSMENT CLINICAL REPORT       ")
    summary.append("==================================================")
    summary.append("")
    summary.append(f"Total Vertebrae Detected : {data.get('detection_count', 0)}")
    summary.append(f"Image Resolution         : {data.get('input_shape', [0,0])[1]}x{data.get('input_shape', [0,0])[0]} pixels")
    summary.append("")
    summary.append("----------------- COBB MEASUREMENTS -----------------")
    
    selected_cobb = data.get("selected_cobb_angle", 0.0)
    summary.append(f"Primary Cobb Curvature   : {selected_cobb:.2f}°")
    
    # Classify severity of scoliosis based on Cobb Angle
    # Mild: 10 - 24 degrees, Moderate: 25 - 40 degrees, Severe: > 40 degrees
    if selected_cobb < 10:
        severity = "Normal / Within Physiological Range"
    elif selected_cobb < 25:
        severity = "MILD SCOLIOSIS"
    elif selected_cobb <= 40:
        severity = "MODERATE SCOLIOSIS"
    else:
        severity = "SEVERE SCOLIOSIS (Requires Orthopedic Consultation)"
        
    summary.append(f"Clinical Classification  : {severity}")
    summary.append("")
    summary.append("------------------- ANGLE PAIRS -------------------")
    
    angle_pairs = data.get("angle_pairs", [])
    for idx, pair in enumerate(angle_pairs):
        u_idx = pair.get("upper_detection_index")
        l_idx = pair.get("lower_detection_index")
        cobb = pair.get("cobb_angle", 0.0)
        u_obl = pair.get("upper_oblique", 0.0)
        l_obl = pair.get("lower_oblique", 0.0)
        
        summary.append(f"Curve Pair #{idx+1}:")
        summary.append(f"  - Upper End Vertebra (index {u_idx}) Tilt : {u_obl:.2f}°")
        summary.append(f"  - Lower End Vertebra (index {l_idx}) Tilt : {l_obl:.2f}°")
        summary.append(f"  - Calculated Cobb Curvature Angle   : {cobb:.2f}°")
        summary.append("")
        
    summary.append("==================================================")
    summary.append("Report generated by Scoliosis AI Suite.")
    return "\n".join(summary)
